[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HOODESolver = "217528c2-21c4-4222-9975-97f0b0cbd7c1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
